-- Best-effort reconstruction of the public schema, generated by querying
-- information_schema/pg_catalog directly (no pg_dump — Docker isn't
-- available in this environment). NOT a byte-perfect pg_dump:
--   - Table order is alphabetical, not dependency order — foreign keys
--     may reference tables defined later in this file. Reorder or wrap in
--     a transaction with constraints deferred if you ever need to replay it.
--   - Covers tables/constraints/indexes/RLS policies/functions only. Does
--     NOT include triggers, custom types/enums, extensions, storage
--     buckets, or auth schema config — those must be recreated separately.
--   - This is a schema snapshot only — it has NO DATA. Pair with
--     backups/<timestamp>/data.json before relying on this for disaster
--     recovery.
-- Regenerated: 2026-07-26

-- ============================================
create table if not exists public.balance_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_id uuid,
  amount_mdl numeric NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.balance_adjustments enable row level security;

alter table balance_adjustments add constraint balance_adjustments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
alter table balance_adjustments add constraint balance_adjustments_pkey PRIMARY KEY (id);
alter table balance_adjustments add constraint balance_adjustments_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id);

create policy balance_adjustments_select_own on public.balance_adjustments for SELECT to public using ((user_id = ( SELECT auth.uid() AS uid)));


-- ============================================
create table if not exists public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id bigint NOT NULL,
  buyer_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  scheduled_delete_at timestamp with time zone,
  has_open_ticket boolean DEFAULT false,
  hidden_for uuid[] DEFAULT '{}'::uuid[]
);

alter table public.conversations enable row level security;

alter table conversations add constraint conversations_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table conversations add constraint conversations_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE;
alter table conversations add constraint conversations_pkey PRIMARY KEY (id);
alter table conversations add constraint conversations_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table conversations add constraint unique_buyer_item UNIQUE (item_id, buyer_id);

CREATE INDEX idx_conversations_buyer ON public.conversations USING btree (buyer_id);
CREATE INDEX idx_conversations_item ON public.conversations USING btree (item_id);
CREATE INDEX idx_conversations_scheduled_delete ON public.conversations USING btree (scheduled_delete_at) WHERE (scheduled_delete_at IS NOT NULL);
CREATE INDEX idx_conversations_seller ON public.conversations USING btree (seller_id);
CREATE INDEX idx_conversations_updated ON public.conversations USING btree (updated_at DESC);

create policy "Buyer can create conversation" on public.conversations for INSERT to public with check ((( SELECT auth.uid() AS uid) = buyer_id));
create policy "Users can hide their own conversations" on public.conversations for UPDATE to public using (((( SELECT auth.uid() AS uid) = buyer_id) OR (( SELECT auth.uid() AS uid) = seller_id))) with check (((( SELECT auth.uid() AS uid) = buyer_id) OR (( SELECT auth.uid() AS uid) = seller_id)));
create policy "Users see own conversations" on public.conversations for SELECT to public using (((( SELECT auth.uid() AS uid) = buyer_id) OR (( SELECT auth.uid() AS uid) = seller_id)));


-- ============================================
create table if not exists public.dispute_evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispute_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  type evidence_type NOT NULL,
  storage_path text,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.dispute_evidence enable row level security;

alter table dispute_evidence add constraint dispute_evidence_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES disputes(id) ON DELETE CASCADE;
alter table dispute_evidence add constraint dispute_evidence_pkey PRIMARY KEY (id);
alter table dispute_evidence add constraint dispute_evidence_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id);

create policy dispute_evidence_select_combined on public.dispute_evidence for SELECT to public using (((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))) OR (EXISTS ( SELECT 1
   FROM (disputes d
     JOIN orders o ON ((o.id = d.order_id)))
  WHERE ((d.id = dispute_evidence.dispute_id) AND ((o.buyer_id = ( SELECT auth.uid() AS uid)) OR (o.seller_id = ( SELECT auth.uid() AS uid))))))));
create policy evidence_insert_participant on public.dispute_evidence for INSERT to public with check (((( SELECT auth.uid() AS uid) = uploaded_by) AND (EXISTS ( SELECT 1
   FROM (disputes d
     JOIN orders o ON ((o.id = d.order_id)))
  WHERE ((d.id = dispute_evidence.dispute_id) AND ((o.buyer_id = ( SELECT auth.uid() AS uid)) OR (o.seller_id = ( SELECT auth.uid() AS uid))) AND (d.status = ANY (ARRAY['open'::dispute_status, 'under_review'::dispute_status])))))));


-- ============================================
create table if not exists public.dispute_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispute_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  body text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.dispute_messages enable row level security;

alter table dispute_messages add constraint dispute_messages_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 2000)));
alter table dispute_messages add constraint dispute_messages_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES disputes(id) ON DELETE CASCADE;
alter table dispute_messages add constraint dispute_messages_pkey PRIMARY KEY (id);
alter table dispute_messages add constraint dispute_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id);

create policy dispute_messages_insert_combined on public.dispute_messages for INSERT to public with check ((((( SELECT auth.uid() AS uid) = sender_id) AND (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))) AND (EXISTS ( SELECT 1
   FROM disputes d
  WHERE ((d.id = dispute_messages.dispute_id) AND (d.status = ANY (ARRAY['open'::dispute_status, 'under_review'::dispute_status])))))) OR ((( SELECT auth.uid() AS uid) = sender_id) AND (EXISTS ( SELECT 1
   FROM (disputes d
     JOIN orders o ON ((o.id = d.order_id)))
  WHERE ((d.id = dispute_messages.dispute_id) AND ((o.buyer_id = ( SELECT auth.uid() AS uid)) OR (o.seller_id = ( SELECT auth.uid() AS uid))) AND (d.status = ANY (ARRAY['open'::dispute_status, 'under_review'::dispute_status]))))))));
create policy dispute_messages_select_combined on public.dispute_messages for SELECT to public using (((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))) OR (EXISTS ( SELECT 1
   FROM (disputes d
     JOIN orders o ON ((o.id = d.order_id)))
  WHERE ((d.id = dispute_messages.dispute_id) AND ((o.buyer_id = ( SELECT auth.uid() AS uid)) OR (o.seller_id = ( SELECT auth.uid() AS uid))))))));


-- ============================================
create table if not exists public.disputes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  opened_by uuid NOT NULL,
  reason text NOT NULL,
  status dispute_status NOT NULL DEFAULT 'open'::dispute_status,
  admin_note text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  split_refund_pct numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  buyer_offer_pct numeric,
  offer_status text NOT NULL DEFAULT 'none'::text,
  return_stage text NOT NULL DEFAULT 'none'::text,
  return_tracking_number text,
  return_shipping_cost_mdl numeric,
  return_shipped_at timestamp with time zone,
  return_received_at timestamp with time zone
);

alter table public.disputes enable row level security;

alter table disputes add constraint disputes_buyer_offer_pct_check CHECK (((buyer_offer_pct IS NULL) OR ((buyer_offer_pct >= (0)::numeric) AND (buyer_offer_pct <= (100)::numeric))));
alter table disputes add constraint disputes_offer_status_check CHECK ((offer_status = ANY (ARRAY['none'::text, 'pending'::text, 'accepted'::text, 'rejected'::text])));
alter table disputes add constraint disputes_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES auth.users(id);
alter table disputes add constraint disputes_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table disputes add constraint disputes_order_id_key UNIQUE (order_id);
alter table disputes add constraint disputes_pkey PRIMARY KEY (id);
alter table disputes add constraint disputes_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id);
alter table disputes add constraint disputes_return_shipping_cost_mdl_check CHECK (((return_shipping_cost_mdl IS NULL) OR (return_shipping_cost_mdl >= (0)::numeric)));
alter table disputes add constraint disputes_return_stage_check CHECK ((return_stage = ANY (ARRAY['none'::text, 'awaiting_return'::text, 'shipped'::text, 'received'::text])));

CREATE INDEX idx_disputes_order ON public.disputes USING btree (order_id);

create policy disputes_insert_buyer on public.disputes for INSERT to public with check (((( SELECT auth.uid() AS uid) = opened_by) AND (EXISTS ( SELECT 1
   FROM orders o
  WHERE ((o.id = disputes.order_id) AND (o.buyer_id = ( SELECT auth.uid() AS uid)) AND (o.status = 'shipped'::order_status))))));
create policy disputes_select_combined on public.disputes for SELECT to public using (((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))) OR (EXISTS ( SELECT 1
   FROM orders o
  WHERE ((o.id = disputes.order_id) AND ((o.buyer_id = ( SELECT auth.uid() AS uid)) OR (o.seller_id = ( SELECT auth.uid() AS uid))))))));
create policy disputes_update_combined on public.disputes for UPDATE to public using ((((( SELECT auth.uid() AS uid) = opened_by) AND (status = 'open'::dispute_status)) OR ((( SELECT auth.uid() AS uid) = opened_by) AND (return_stage = 'awaiting_return'::text)) OR ((EXISTS ( SELECT 1
   FROM orders o
  WHERE ((o.id = disputes.order_id) AND (o.seller_id = ( SELECT auth.uid() AS uid))))) AND (offer_status = 'pending'::text)))) with check ((((( SELECT auth.uid() AS uid) = opened_by) AND (status = 'open'::dispute_status) AND (offer_status = 'pending'::text)) OR ((( SELECT auth.uid() AS uid) = opened_by) AND (return_stage = 'shipped'::text) AND (return_tracking_number IS NOT NULL) AND (return_shipping_cost_mdl IS NOT NULL)) OR ((offer_status = 'rejected'::text) AND (status = 'under_review'::dispute_status))));


-- ============================================
create table if not exists public.escrow_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  type escrow_tx_type NOT NULL,
  amount_mdl numeric NOT NULL,
  stripe_id text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.escrow_transactions enable row level security;

alter table escrow_transactions add constraint escrow_transactions_amount_mdl_check CHECK ((amount_mdl > (0)::numeric));
alter table escrow_transactions add constraint escrow_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table escrow_transactions add constraint escrow_transactions_pkey PRIMARY KEY (id);

CREATE INDEX idx_escrow_order ON public.escrow_transactions USING btree (order_id);

create policy escrow_select_participant on public.escrow_transactions for SELECT to public using ((EXISTS ( SELECT 1
   FROM orders o
  WHERE ((o.id = escrow_transactions.order_id) AND ((o.buyer_id = ( SELECT auth.uid() AS uid)) OR (o.seller_id = ( SELECT auth.uid() AS uid)))))));


-- ============================================
create table if not exists public.favorites (
  id bigint NOT NULL,
  user_id uuid NOT NULL,
  item_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.favorites enable row level security;

alter table favorites add constraint favorites_pkey PRIMARY KEY (id);
alter table favorites add constraint favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table favorites add constraint favorites_user_id_item_id_key UNIQUE (user_id, item_id);

CREATE INDEX favorites_item_id_idx ON public.favorites USING btree (item_id);
CREATE INDEX favorites_user_id_idx ON public.favorites USING btree (user_id);
CREATE INDEX favorites_user_item_idx ON public.favorites USING btree (user_id, item_id);

create policy favorites_delete_own on public.favorites for DELETE to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
create policy favorites_insert_own on public.favorites for INSERT to authenticated with check ((( SELECT auth.uid() AS uid) = user_id));
create policy favorites_select_all_auth on public.favorites for SELECT to authenticated using (true);


-- ============================================
create table if not exists public.items (
  id bigint NOT NULL DEFAULT nextval('items_id_seq'::regclass),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  price numeric NOT NULL,
  category text,
  images text[] DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  category_key text,
  category_path jsonb NOT NULL DEFAULT '[]'::jsonb,
  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text
);

alter table public.items enable row level security;

alter table items add constraint items_pkey PRIMARY KEY (id);
alter table items add constraint items_price_check CHECK ((price >= (0)::numeric));
alter table items add constraint items_status_check CHECK ((status = ANY (ARRAY['active'::text, 'reserved'::text, 'sold'::text, 'deleted'::text])));
alter table items add constraint items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_items_category_key ON public.items USING btree (category_key);

create policy "Anyone can view items" on public.items for SELECT to public using (true);
create policy "Authenticated users can insert own items" on public.items for INSERT to public with check (((( SELECT auth.uid() AS uid) IS NOT NULL) AND (user_id = ( SELECT auth.uid() AS uid))));
create policy "Users can delete own items" on public.items for DELETE to public using (((( SELECT auth.uid() AS uid) = user_id) AND (status = 'active'::text)));
create policy "Users can update own items" on public.items for UPDATE to public using (((( SELECT auth.uid() AS uid) = user_id) AND (status = 'active'::text))) with check ((( SELECT auth.uid() AS uid) = user_id));


-- ============================================
create table if not exists public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  deleted_at timestamp with time zone
);

alter table public.messages enable row level security;

alter table messages add constraint messages_content_check CHECK ((char_length(content) > 0));
alter table messages add constraint messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
alter table messages add constraint messages_pkey PRIMARY KEY (id);
alter table messages add constraint messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_messages_conversation ON public.messages USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_messages_sender ON public.messages USING btree (sender_id);

create policy "Participants see messages" on public.messages for SELECT to public using ((EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.buyer_id = ( SELECT auth.uid() AS uid)) OR (c.seller_id = ( SELECT auth.uid() AS uid)))))));
create policy "Participants send messages" on public.messages for INSERT to public with check (((( SELECT auth.uid() AS uid) = sender_id) AND (EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.buyer_id = ( SELECT auth.uid() AS uid)) OR (c.seller_id = ( SELECT auth.uid() AS uid))))))));
create policy messages_update_combined on public.messages for UPDATE to public using (((EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.buyer_id = ( SELECT auth.uid() AS uid)) OR (c.seller_id = ( SELECT auth.uid() AS uid)))))) OR (( SELECT auth.uid() AS uid) = sender_id))) with check (((( SELECT auth.uid() AS uid) <> sender_id) OR (( SELECT auth.uid() AS uid) = sender_id)));


-- ============================================
create table if not exists public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  order_id uuid,
  title text NOT NULL,
  body text NOT NULL,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.notifications enable row level security;

alter table notifications add constraint notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table notifications add constraint notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX notifications_user_id_created_at_idx ON public.notifications USING btree (user_id, created_at DESC);

create policy notifications_insert_admin on public.notifications for INSERT to public with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))));
create policy notifications_select_owner on public.notifications for SELECT to public using ((( SELECT auth.uid() AS uid) = user_id));
create policy notifications_update_owner on public.notifications for UPDATE to public using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));


-- ============================================
create table if not exists public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  item_id bigint NOT NULL,
  status order_status NOT NULL DEFAULT 'pending_payment'::order_status,
  price_mdl numeric NOT NULL,
  fee_pct numeric NOT NULL DEFAULT 0,
  fee_mdl numeric NOT NULL DEFAULT 0,
  net_mdl numeric NOT NULL,
  stripe_payment_intent_id text,
  stripe_charge_id text,
  stripe_transfer_id text,
  stripe_refund_id text,
  shipping_address jsonb,
  courier_name text,
  tracking_number text,
  paid_at timestamp with time zone,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  auto_release_at timestamp with time zone,
  scheduled_delete_at timestamp with time zone,
  has_open_ticket boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.orders enable row level security;

alter table orders add constraint buyer_ne_seller CHECK ((buyer_id <> seller_id));
alter table orders add constraint net_lte_price CHECK ((net_mdl <= price_mdl));
alter table orders add constraint orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES auth.users(id);
alter table orders add constraint orders_fee_mdl_check CHECK ((fee_mdl >= (0)::numeric));
alter table orders add constraint orders_fee_pct_check CHECK ((fee_pct >= (0)::numeric));
alter table orders add constraint orders_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id);
alter table orders add constraint orders_net_mdl_check CHECK ((net_mdl >= (0)::numeric));
alter table orders add constraint orders_pkey PRIMARY KEY (id);
alter table orders add constraint orders_price_mdl_check CHECK ((price_mdl > (0)::numeric));
alter table orders add constraint orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id);
alter table orders add constraint orders_stripe_payment_intent_id_key UNIQUE (stripe_payment_intent_id);

CREATE INDEX idx_orders_auto_release ON public.orders USING btree (auto_release_at) WHERE (status = 'shipped'::order_status);
CREATE INDEX idx_orders_buyer ON public.orders USING btree (buyer_id);
CREATE INDEX idx_orders_cleanup ON public.orders USING btree (scheduled_delete_at) WHERE (status = ANY (ARRAY['completed'::order_status, 'refunded'::order_status, 'cancelled'::order_status]));
CREATE INDEX idx_orders_item ON public.orders USING btree (item_id);
CREATE INDEX idx_orders_seller ON public.orders USING btree (seller_id);
CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE INDEX idx_orders_stripe_pi ON public.orders USING btree (stripe_payment_intent_id) WHERE (stripe_payment_intent_id IS NOT NULL);

create policy orders_insert_buyer on public.orders for INSERT to public with check ((( SELECT auth.uid() AS uid) = buyer_id));
create policy orders_select_combined on public.orders for SELECT to public using (((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))) OR ((( SELECT auth.uid() AS uid) = buyer_id) OR (( SELECT auth.uid() AS uid) = seller_id))));
create policy orders_update_combined on public.orders for UPDATE to public using ((((( SELECT auth.uid() AS uid) = buyer_id) AND (status = 'shipped'::order_status)) OR ((( SELECT auth.uid() AS uid) = seller_id) AND (status = 'paid'::order_status)))) with check (((status = ANY (ARRAY['delivered'::order_status, 'disputed'::order_status])) OR ((status = 'shipped'::order_status) AND (tracking_number IS NOT NULL) AND (courier_name IS NOT NULL))));


-- ============================================
create table if not exists public.profiles (
  id uuid NOT NULL,
  username text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  push_token text,
  is_admin boolean NOT NULL DEFAULT false
);

alter table public.profiles enable row level security;

alter table profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table profiles add constraint profiles_pkey PRIMARY KEY (id);

create policy "Own insert" on public.profiles for INSERT to public with check ((( SELECT auth.uid() AS uid) = id));
create policy "Own update" on public.profiles for UPDATE to public using ((( SELECT auth.uid() AS uid) = id));
create policy "Public read" on public.profiles for SELECT to public using (true);


-- ============================================
create table if not exists public.seller_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  rating smallint NOT NULL,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.seller_reviews enable row level security;

alter table seller_reviews add constraint seller_reviews_comment_check CHECK ((char_length(comment) <= 500));
alter table seller_reviews add constraint seller_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table seller_reviews add constraint seller_reviews_order_id_reviewer_id_key UNIQUE (order_id, reviewer_id);
alter table seller_reviews add constraint seller_reviews_pkey PRIMARY KEY (id);
alter table seller_reviews add constraint seller_reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
alter table seller_reviews add constraint seller_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES auth.users(id);
alter table seller_reviews add constraint seller_reviews_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES auth.users(id);

CREATE INDEX idx_reviews_seller ON public.seller_reviews USING btree (seller_id);

create policy reviews_insert_buyer on public.seller_reviews for INSERT to public with check (((( SELECT auth.uid() AS uid) = reviewer_id) AND (EXISTS ( SELECT 1
   FROM orders o
  WHERE ((o.id = seller_reviews.order_id) AND (o.buyer_id = ( SELECT auth.uid() AS uid)) AND (o.status = 'completed'::order_status))))));
create policy reviews_select_public on public.seller_reviews for SELECT to public using (true);


-- ============================================
create table if not exists public.shipping_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  label text NOT NULL DEFAULT 'Acasă'::text,
  full_name text NOT NULL,
  phone text NOT NULL,
  city text NOT NULL,
  address text NOT NULL,
  postal_code text,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

alter table public.shipping_addresses enable row level security;

alter table shipping_addresses add constraint shipping_addresses_pkey PRIMARY KEY (id);
alter table shipping_addresses add constraint shipping_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_addresses_user ON public.shipping_addresses USING btree (user_id);

create policy addresses_owner_all on public.shipping_addresses for ALL to public using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));


-- ============================================
create table if not exists public.withdrawal_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount_mdl numeric NOT NULL,
  card_holder_name text NOT NULL,
  card_number_last4 text NOT NULL,
  status withdrawal_status NOT NULL DEFAULT 'pending'::withdrawal_status,
  admin_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  iban text NOT NULL
);

alter table public.withdrawal_requests enable row level security;

alter table withdrawal_requests add constraint withdrawal_requests_amount_mdl_check CHECK ((amount_mdl > (0)::numeric));
alter table withdrawal_requests add constraint withdrawal_requests_pkey PRIMARY KEY (id);
alter table withdrawal_requests add constraint withdrawal_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX withdrawal_requests_user_id_idx ON public.withdrawal_requests USING btree (user_id);

create policy withdrawal_requests_insert_owner on public.withdrawal_requests for INSERT to public with check ((( SELECT auth.uid() AS uid) = user_id));
create policy withdrawal_requests_select_admin on public.withdrawal_requests for SELECT to public using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))));
create policy withdrawal_requests_select_owner on public.withdrawal_requests for SELECT to public using ((( SELECT auth.uid() AS uid) = user_id));
create policy withdrawal_requests_update_admin on public.withdrawal_requests for UPDATE to public using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin)))) with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = ( SELECT auth.uid() AS uid)) AND profiles.is_admin))));


-- ============================================
-- FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION public.cleanup_expired_conversations()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Șterge mesajele din conversațiile expirate (fără ticket deschis)
  DELETE FROM messages
  WHERE conversation_id IN (
    SELECT id FROM conversations
    WHERE scheduled_delete_at IS NOT NULL
      AND scheduled_delete_at <= NOW()
      AND has_open_ticket = FALSE  
  );

  -- Șterge conversațiile expirate
  DELETE FROM conversations
  WHERE scheduled_delete_at IS NOT NULL
    AND scheduled_delete_at <= NOW()
    AND has_open_ticket = FALSE;
    
  RAISE LOG 'cleanup_expired_conversations: rulat la %', NOW();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_profile_on_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data ->> 'username',
      split_part(NEW.email, '@', 1)
    )
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_single_default_address()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.is_default = true THEN
    UPDATE shipping_addresses
    SET is_default = false
    WHERE user_id = NEW.user_id AND id != NEW.id;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.orders_status_timestamps()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.status = 'paid'      AND OLD.status != 'paid'      THEN
    NEW.paid_at = now();
  END IF;
  IF NEW.status = 'shipped'   AND OLD.status != 'shipped'   THEN
    NEW.shipped_at      = now();
    NEW.auto_release_at = now() + INTERVAL '14 days';
  END IF;
  IF NEW.status = 'delivered' AND OLD.status != 'delivered' THEN
    NEW.delivered_at = now();
  END IF;
  IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
    NEW.completed_at        = now();
    NEW.scheduled_delete_at = now() + INTERVAL '7 days';
  END IF;
  IF NEW.status IN ('cancelled','refunded')
     AND OLD.status NOT IN ('cancelled','refunded') THEN
    NEW.cancelled_at        = now();
    NEW.scheduled_delete_at = now() + INTERVAL '7 days';
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_scheduled_delete()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.completed_at IS NOT NULL AND OLD.completed_at IS NULL THEN
    NEW.scheduled_delete_at := NEW.completed_at + INTERVAL '7 days';
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_item_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.status = 'paid' AND OLD.status = 'pending_payment' THEN
    UPDATE public.items SET status = 'reserved' WHERE id = NEW.item_id;

  ELSIF NEW.status = 'completed' THEN
    UPDATE public.items SET status = 'sold'     WHERE id = NEW.item_id;

  ELSIF NEW.status IN ('refunded','cancelled')
        AND OLD.status NOT IN ('refunded','cancelled') THEN
    UPDATE public.items SET status = 'active'   WHERE id = NEW.item_id;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_open_ticket_flag()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE orders SET has_open_ticket = true,  status = 'disputed'
    WHERE id = NEW.order_id;
  END IF;
  IF TG_OP = 'UPDATE'
     AND NEW.status IN ('resolved_release','resolved_refund','resolved_split','closed')
     AND OLD.status NOT IN ('resolved_release','resolved_refund','resolved_split','closed') THEN
    UPDATE orders SET has_open_ticket = false WHERE id = NEW.order_id;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_conversation_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE conversations
  SET updated_at = now()
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$function$
;