#!/usr/bin/env node
// Manual backup helper (no Docker/pg_dump available in this environment).
// Usage: node scripts/backup.js
//   - schema  -> supabase/schema_baseline_reference.sql (safe to commit, no data)
//   - data    -> backups/<timestamp>/data.json (gitignored, real user data)

const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

function runQuery(sqlFile) {
  const out = execFileSync(
    "npx",
    ["supabase", "db", "query", "--file", sqlFile, "--linked", "--output", "json"],
    { cwd: ROOT, encoding: "utf8", shell: true },
  );
  const jsonStart = out.indexOf("{");
  const parsed = JSON.parse(out.slice(jsonStart));
  return parsed.rows[0];
}

function backupSchema() {
  console.log("Exporting schema...");
  const row = runQuery(path.join("scripts", "export-schema.sql"));
  const header = `-- Best-effort reconstruction of the public schema, generated by querying
-- information_schema/pg_catalog directly (no pg_dump — Docker isn't
-- available in this environment). NOT a byte-perfect pg_dump:
--   - Table order is alphabetical, not dependency order — foreign keys
--     may reference tables defined later in this file. Reorder or wrap in
--     a transaction with constraints deferred if you ever need to replay it.
--   - Covers tables/constraints/indexes/RLS policies/functions only. Does
--     NOT include triggers, custom types/enums, extensions, storage
--     buckets, or auth schema config — those must be recreated separately.
--   - This is a schema snapshot only — it has NO DATA. Pair with
--     backups/<timestamp>/data.json before relying on this for disaster
--     recovery.
-- Regenerated: ${new Date().toISOString().slice(0, 10)}

`;
  const dest = path.join(ROOT, "supabase", "schema_baseline_reference.sql");
  fs.writeFileSync(dest, header + row.full_schema, "utf8");
  console.log("  ->", dest);
}

function backupData() {
  console.log("Exporting data...");
  const row = runQuery(path.join("scripts", "export-data.sql"));
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const dir = path.join(ROOT, "backups", stamp);
  fs.mkdirSync(dir, { recursive: true });
  const dest = path.join(dir, "data.json");
  fs.writeFileSync(dest, JSON.stringify(row.full_data, null, 2), "utf8");
  console.log("  ->", dest);
}

backupSchema();
backupData();
console.log("Done.");
